[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
default_command = "./bin/polkadot"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  ws_port = 9900
  extra_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  extra_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "charlie"
  validator = true
  extra_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "dave"
  validator = true
  extra_args = [ "-lparachain=debug" ]


[[parachains]]
id = 2000
add_to_genesis = true
cumulus_based = true
chain = "template-rococo"

  [[parachains.collators]]
  name = "template-collator01"
  command = "./target/release/parachain-template-node"
  ws_port = 9920
  args = ["--log=xcm=trace"]

  [[parachains.collators]]
  name = "template-collator02"
  command = "./target/release/parachain-template-node"
  ws_port = 9921
  args = ["--log=xcm=trace"]